"""add_user_role

Revision ID: b7aa03eb6285
Revises: 8f0cd2851a6b
Create Date: 2025-01-06 XX:XX:XX.XXXXXX

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7aa03eb6285'
down_revision: Union[str, None] = '8f0cd2851a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero verificar si la tabla existe y añadir columna role si no existe
    try:
        op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='student'))
    except Exception:
        # Si la tabla no existe o la columna ya existe, continuar
        pass
    
    # Comentar las otras operaciones problemáticas por ahora
    # op.alter_column('users', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('users', 'full_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('users', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.drop_column('users', 'updated_at')
    # op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    # op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # op.alter_column('users', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # op.alter_column('users', 'full_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
